# Generated by Django 3.2.25 on 2025-07-19 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250719_1655'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.city'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employers', to='core.city'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
