# Generated by Django 3.2.25 on 2025-07-19 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20250719_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 14-digit Egyptian National ID.', regex='^(2|3)[0-9]{2}(0[1-9]|1[0-2])(0[1-9]|[12][0-9]|3[01])[0-9]{7}$')]),
        ),
    ]
