# Generated by Django 3.2.25 on 2025-07-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_employee_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
