# Generated by Django 3.2.25 on 2025-07-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_employee_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('intern', 'Intern'), ('junior', 'Junior'), ('mid-level', 'Mid-level'), ('senior', 'Senior'), ('expert', 'Expert')], max_length=50, null=True),
        ),
    ]
