# Generated by Django 3.2.25 on 2025-07-21 16:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250719_1655'),
        ('user', '0004_alter_employee_experience_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 11-digit Egyptian mobile number starting with 010, 011, 012, or 015.', regex='^01[0125][0-9]{8}$')]),
        ),
        migrations.AlterField(
            model_name='employer',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employers', to='core.city'),
        ),
    ]
