# Generated by Django 3.2.25 on 2025-07-15 00:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('employee', 'Employee'), ('employer', 'Employer'), ('admin', 'Admin')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
