# Generated by Django 3.2.25 on 2025-07-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20250715_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('employee', 'Employee'), ('employer', 'Employer'), ('admin', 'Admin')], max_length=15),
        ),
    ]
